app:
  security:
    jwt:
      access-token:
        expiration: 20
      issuer: QLTC coporation
      refresh-token:
        expiration: 10
      secret: ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuwxyz+9-$!*&%   
server:
  servlet:
    context-path: /api/v1/quanlychitieu
spring:
  application:
    name: QuanLyChiTieuService
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/quanlychitieudb
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10485760
      max-request-size: 10485760
  security:
    oauth2:
      client:
        registration:
           google:
              client-id: 631955864223-tiiq4u9ebgq65krr2b308m1n73plr7k5.apps.googleusercontent.com
              client-secret: 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
              scope:
                  - email
                  - profile
              redirect-uri: http://localhost:8080/login/oauth2/code/google        
      
